### ISSUE TITLE
Which image is for what?

### ISSUE THREAD

**Issue by milkpirate** [kscheff/BlueBasic#15]
Hey, you have quite some images in the [hex folder](https://github.com/kscheff/BlueBasic/tree/master/hex) could you elaborate a little which image is for what, with which feature and for which device (CC2540 / CC2541 <- is espaccially interesting for me).

I mean where the difference between `BlueBattery-BBX.*` vs. `BlueBattery-D1.*` vs. `BlueBasic-BlueBattery-MPPT.*` vs. `BlueBasic-BlueBattery.*` vs. `BlueBasic-BlueSolar.*` vs. `BlueBasic-BlueSteca.*` ?

Best regards :)

**Comment by kscheff** [comment]
They have different combination of features enabled, so it fits the memory and application needs. The most generic Version without bells and whistles is the `BlueBasic-BlueBattery` version. The `-BBX`Version carries a different memory layout, increasing the available programming space from 8 to 10 pages. See attached memory map.

[CC2541 BlueBattery Page Memory Map - Sheet1-2.pdf](https://github.com/kscheff/BlueBasic/files/6072218/CC2541.BlueBattery.Page.Memory.Map.-.Sheet1-2.pdf)

I changed the memory concept, so that ImgB contains the actual BASIC program. In this way an Img/B always contains a BASIC program. To maintain compatibility in the field, the Pages 82-85 (old location of Tim's version) are unused. In order to incorporate a BASIC program I use a different external script to compile the BASIC code into the image. For BBX I changed the memory layout, thus not compatible to old boot loader / ImgA increasing the available ImgB area and BASIC program memory.
