### ISSUE TITLE
How to recover after REBOOT UP command?

### ISSUE THREAD

**Issue by 0xFACE** [kscheff/BlueBasic#19]
Any chance to recover the device after REBOOT UP command?
OAD by TI Simplelink for Android is not working for me.
Do i need to use a programmer to reflash?

**Comment by kscheff** [comment]
Reset usually boots back into image B in case the image is still OK. 

If that’s not working, the TI OAD does not work with images >128K due to a bug in their upload code. You can use BlueBattery App from iOS App Store. First connect to the device and cancel the upload but stay connected  Then open a .bin file from email and select as target BlueBattery…. The App will then download any image. 

☀️Grüsse 
Kai Scheffer
Blue-Battery.com
+41 78 735 8842 (auch WhatsApp, FaceTime, Signal, Telegram)

**Comment by 0xFACE** [comment]
Thanks for the reply.
Unfortunately, I don't have an Apple device here. Power cycle and hard reset also does not restore the device back to work.
It looks like I need to connect to the programmer again :(.
