### ISSUE TITLE
Firmware for HM-10 modules without external XTAL

### ISSUE THREAD

**Issue by 0xFACE** [kscheff/BlueBasic#6]
Is it possible to prepare firmware for HM-10 modules without external XTAL?
I found many of cheap modules on Ebay without 32kHz  XTAL wont work with BlueBasic.  
AFAIK with special build flag we can force chips to use internal oscillator. 

Best regards

**Comment by kscheff** [comment]
Without 32 KHz xtal you loose sleep functionality. I also saw cheap modules recently, but I am using JDY-08 modules since some time know. They are cheap as well (around $1.70) and they recently got FCC approval. So it might not be worth the hassle to change the firmware. I have about 300 modules so far deployed they are all running BlueBasic.

**Comment by 0xFACE** [comment]
Thank you, apparently I overlooked this module.
